# Default values for fynd_chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: fynd-chart
image:
  repository: jainankur2/project4
  pullPolicy: IfNotPresent
  tag: "26"

service:
  name: Node2
  type: NodePort 
  targetPort: 30080
  servicePort: 80

